const FENCE_START = '```json'
const FENCE_END = '```'

export function renderQueueMarkdown(state) {
  const { cap, generatedAt, entries, conflicts } = state
  const stateBlock = JSON.stringify({ cap, generatedAt, entries, conflicts }, null, 2)
  const orderedList = entries
    .map((e, i) => `${i + 1}. #${e.issue} — ${e.bugOrFeature} — difficulty ${e.difficulty} — ${e.title}`)
    .join('\n')
  return `# Issue Factory Queue

_Generated by \`/factory triage\`. Do not hand-edit the JSON block below — rerun \`/factory triage\` instead._

## State

${FENCE_START}
${stateBlock}
${FENCE_END}

## Queue (ordered)

${orderedList || '(empty)'}
`
}

export function parseQueueMarkdown(text) {
  const startIdx = text.indexOf(FENCE_START)
  if (startIdx === -1) throw new Error('No JSON state block found in queue.md')
  const afterStart = startIdx + FENCE_START.length
  const endIdx = text.indexOf(FENCE_END, afterStart)
  if (endIdx === -1) throw new Error('Unterminated JSON state block in queue.md')
  const json = text.slice(afterStart, endIdx).trim()
  return JSON.parse(json)
}
